spring:
  datasource:
    url: jdbc:postgresql://${db-source.host}/${db-source.name}
    username: ${db-source.username}
    password: ${db-source.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

db-source:
  host: ${DATABASE_HOST}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  name: ${DATABASE_NAME}


feign_custom:
  retry.max: 5
  retry.interval:

feign:
  client:
    config:
      default:
        connect-timeout: 160000000
        readTimeout: 160000000
        loggerLevel: full
        error-decoder: com.lightfeather.personalinfolightfeather.config.FeignErrorDecoder
        retryer: com.lightfeather.personalinfolightfeather.config.FeignRetrier

client:
  supervisor_baseurl: ${SUPERVISOR_ENDPOINT}
